/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class ChangePassword extends javax.swing.JPanel {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        match = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        new2 = new javax.swing.JPasswordField();
        old = new javax.swing.JPasswordField();
        new1 = new javax.swing.JPasswordField();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(760, 261));
        setLayout(null);
        add(match);
        match.setBounds(460, 250, 270, 40);

        jLabel1.setText("confirm Password");
        add(jLabel1);
        jLabel1.setBounds(330, 140, 120, 30);

        jLabel2.setText("old Password");
        add(jLabel2);
        jLabel2.setBounds(330, 60, 110, 30);

        jLabel3.setText("new password");
        add(jLabel3);
        jLabel3.setBounds(330, 100, 110, 30);

        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(460, 190, 110, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/Picture111.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(-30, 30, 340, 230);

        jButton2.setText("change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(620, 190, 110, 40);

        new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new2ActionPerformed(evt);
            }
        });
        add(new2);
        new2.setBounds(470, 140, 260, 30);

        old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldActionPerformed(evt);
            }
        });
        add(old);
        old.setBounds(470, 60, 260, 30);

        new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new1ActionPerformed(evt);
            }
        });
        add(new1);
        new1.setBounds(470, 100, 260, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (new1.getText().equals(new2.getText()))
        {
            try {
                if(User.mainUser.setPassword(new1.getText(), old.getText()))
                {
                    match.setText("Password Successfully Changed");
                    
                }
                else
                {
                    match.setText("Wrong Password!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            match.setText("Passwords Do Not Match!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new2ActionPerformed

    private void oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldActionPerformed

    private void new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel match;
    private javax.swing.JPasswordField new1;
    private javax.swing.JPasswordField new2;
    private javax.swing.JPasswordField old;
    // End of variables declaration//GEN-END:variables
}
