/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.Membership;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dell
 */
public class addMembership extends javax.swing.JPanel {

    /**
     * Creates new form addMembership
     */
    public addMembership() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        success = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        months = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(663, 300));
        setLayout(null);
        add(success);
        success.setBounds(290, 250, 190, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Add Membership");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(70, 240, 160, 30);

        months.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        months.setForeground(new java.awt.Color(0, 153, 153));
        add(months);
        months.setBounds(290, 170, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Memberhip Period ( In Months) : ");
        add(jLabel4);
        jLabel4.setBounds(60, 170, 230, 30);

        cost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(0, 153, 153));
        add(cost);
        cost.setBounds(210, 110, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Membership Cost :");
        add(jLabel3);
        jLabel3.setBounds(60, 110, 150, 30);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 153, 153));
        add(name);
        name.setBounds(210, 50, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Membership Name :");
        add(jLabel2);
        jLabel2.setBounds(64, 50, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/test.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 663, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (!name.getText().equals("") && !cost.getText().equals("") && !months.getText().equals(""))
        {
            try {
                Membership.addNewMemType(name.getText(), Double.parseDouble(cost.getText()), Integer.parseInt(months.getText()));
                success.setText("Successfully Added ");
            } catch (SQLException ex) {
                Logger.getLogger(addMembership.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(addMembership.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cost;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField months;
    private javax.swing.JTextField name;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
