/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.DataBase;
import database.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class empMainScreen extends javax.swing.JPanel {

    /**
     * Creates new form empMainScreen
     */
    public empMainScreen() {
        initComponents();
        empName.setText(User.mainUser.getName());
        name.setText("Name : " + empName.getText());
        address.setText("Address : " + User.mainUser.getAddressId().toString());
        if (User.mainUser.getGender() == true) {
            gender.setText("Gender : " + "Female");
        } else {
            gender.setText("Gender : " + "Male");
        }
        email.setText("Email : " + User.mainUser.getEmail());
        rank.setText("Rank : " + User.mainUser.getEmp().getRank());
        if (User.mainUser.getEmp().getRank()!=2)
            manager.setEnabled(false);
        DOB.setText(" Date Of Birth : " + User.mainUser.getDateOfBirth());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empName = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        rank = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        manager = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1100, 500));
        setLayout(null);

        gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 153, 153));
        add(gender);
        gender.setBounds(130, 170, 260, 30);

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 153, 153));
        add(email);
        email.setBounds(130, 140, 320, 30);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 153, 153));
        add(name);
        name.setBounds(130, 110, 260, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 102, 0));
        jButton8.setText(" Edit Information");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(190, 330, 200, 31);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/ضضض.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 140, 710);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/Picture111.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(630, 240, 350, 240);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("welcome ");
        add(jLabel3);
        jLabel3.setBounds(140, 50, 120, 30);

        empName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        empName.setForeground(new java.awt.Color(255, 102, 0));
        add(empName);
        empName.setBounds(260, 50, 320, 30);

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(0, 153, 153));
        add(address);
        address.setBounds(130, 270, 550, 30);

        rank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rank.setForeground(new java.awt.Color(0, 153, 153));
        add(rank);
        rank.setBounds(130, 200, 260, 30);

        DOB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DOB.setForeground(new java.awt.Color(0, 153, 153));
        add(DOB);
        DOB.setBounds(130, 230, 260, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Exit");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(590, 450, 110, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("my classes ");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(190, 380, 200, 30);

        manager.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manager.setForeground(new java.awt.Color(0, 153, 153));
        manager.setText("manger options");
        manager.setToolTipText("");
        manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerActionPerformed(evt);
            }
        });
        add(manager);
        manager.setBounds(440, 380, 200, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 102, 0));
        jButton6.setText("Sign Out");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(140, 450, 120, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 102, 0));
        jButton7.setText("change Password");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(440, 330, 200, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DataBase.exitFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            JPanel temp = new ClassesProgram();
            DataBase.changePanel(temp);
        } catch (SQLException ex) {
            Logger.getLogger(empMainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(empMainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerActionPerformed
        // TODO add your handling code here:
        JPanel temp = new mangerOptions();
        DataBase.changePanel(temp);
    }//GEN-LAST:event_managerActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JPanel temp = new LogIn();
        DataBase.changePanel(temp);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JPanel temp = new ChangePassword();
        DataBase.changePanel(temp);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JPanel temp = new editEmployee();
        DataBase.changePanel(temp);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel address;
    private javax.swing.JLabel email;
    private javax.swing.JLabel empName;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manager;
    private javax.swing.JLabel name;
    private javax.swing.JLabel rank;
    // End of variables declaration//GEN-END:variables
}
