/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.Customers;
import database.DataBase;
import database.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import static java.util.Calendar.MONTH;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class FinancialRecord extends javax.swing.JPanel {

    /**
     * Creates new form FinancialRecord
     */
    int cusId;
    
    public FinancialRecord(int cusId) throws SQLException, ClassNotFoundException {
        initComponents();
        this.cusId= cusId;
        String sql = "select * from memcus as m , membership as mem  where m.cusId = "+ cusId + " and mem.memid = m.memid";
        System.out.println(sql);
        DatabaseAPI db = new DatabaseAPI();
        ResultSet set = db.read(sql) ;
        DefaultTableModel model = (DefaultTableModel) fin.getModel();
        while(set.next())
        {
        
                  Calendar c1 = Calendar.getInstance();
                  c1.setTime(set.getDate(3));
           
                  c1.add(MONTH, set.getInt(8));
                  
                  Date t=(Date)c1.getTime();
                  System.out.println(t.toString());
                  SimpleDateFormat dt1 = new SimpleDateFormat("yyyy-MM-ddd");
                  
             model.addRow(new Object[]{  set.getString(6),set.getDouble(7), set.getDate(3),dt1.format(t)});
           
        }
        
         DefaultTableModel model2 = (DefaultTableModel) fin1.getModel();

        String sql2 = "select payment ,paydate  from payments where cusId = "+ cusId;
        set= db.read(sql2);
        while (set.next())
        {
             model2.addRow(new Object[]{set.getDouble(1),set.getDate(2)});
        }
        
        Final.setText("Final Balance :" + Customers.getBalance(cusId) + "$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fin1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fin = new javax.swing.JTable();
        Final = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 560));
        setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(350, 440, 70, 25);

        fin1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        fin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fin1.setForeground(new java.awt.Color(0, 153, 153));
        fin1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment", "Pay Date"
            }
        ));
        jScrollPane2.setViewportView(fin1);

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 90, 170, 200);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(80, 440, 90, 25);

        fin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        fin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fin.setForeground(new java.awt.Color(0, 153, 153));
        fin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Membership", "Cost", "Start Date", "End Date"
            }
        ));
        jScrollPane1.setViewportView(fin);
        if (fin.getColumnModel().getColumnCount() > 0) {
            fin.getColumnModel().getColumn(0).setHeaderValue("Membership");
            fin.getColumnModel().getColumn(2).setHeaderValue("Start Date");
            fin.getColumnModel().getColumn(3).setHeaderValue("End Date");
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(280, 90, 390, 200);

        Final.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Final.setForeground(new java.awt.Color(255, 102, 0));
        Final.setText("Final Balance : 0.00");
        add(Final);
        Final.setBounds(80, 320, 410, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/big.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(400, 280, 390, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/test.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 60, 648);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Financial Record .....................................");
        add(jLabel3);
        jLabel3.setBounds(80, 30, 410, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        if (User.mainUser.getIsEmp()==true)
        {JPanel MembershipPanel = new CustomerForRes(cusId);
         DataBase.changePanel(MembershipPanel);}
        else
        {
            try {
                JPanel MembershipPanel = new Membership1(cusId);
                DataBase.changePanel(MembershipPanel);
            } catch (SQLException ex) {
                Logger.getLogger(FinancialRecord.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FinancialRecord.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DataBase.exitFrame();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Final;
    private javax.swing.JTable fin;
    private javax.swing.JTable fin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
