package Panels;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import database.DataBase;
import database.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Calendar;
import static java.util.Calendar.MONTH;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class Membership1 extends javax.swing.JPanel {
int cusId;
    /**
     * Creates new form Membership
     */
    public Membership1(int cusId) throws SQLException, ClassNotFoundException {
        initComponents();
        this.cusId=cusId;
        String sql="select mem.mounths, mem.cost ,mem.memname , m.startDate from memcus as m , membership as mem where mem.memid = m.memid and  m.cusid= "+cusId;
      //  System.out.println(sql);
        DatabaseAPI db = new DatabaseAPI();
        ResultSet set = db.read(sql);
        // flag=false;
        
        while (set.next()) { 
                  Date d = java.sql.Timestamp.valueOf( LocalDateTime.now());
                  Calendar c1 = Calendar.getInstance();
                  c1.setTime(set.getDate(4));
                  c1.add(MONTH, set.getInt(1));
                  Date t=(Date)c1.getTime();
                  if (d.compareTo(set.getDate(4))* d.compareTo(t)<=0)
                       {
                          type.setText(set.getString(3));
                          start.setText(set.getDate(4).toString());
                          end.setText(t.toString());
                          cost.setText(set.getString(2));    
                       }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 490));
        setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(100, 345, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(100, 270, 80, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Financial Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(70, 210, 160, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/big.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(210, 250, 330, 230);

        cost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(255, 102, 0));
        cost.setText("Membership Cost Per Month : ");
        add(cost);
        cost.setBounds(70, 165, 260, 30);

        end.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        end.setForeground(new java.awt.Color(255, 102, 0));
        end.setText("End Date : ");
        add(end);
        end.setBounds(70, 140, 350, 17);

        start.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        start.setForeground(new java.awt.Color(255, 102, 0));
        start.setText("Start Date : ");
        add(start);
        start.setBounds(70, 105, 300, 20);

        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 102, 0));
        type.setText("Type Of Current Membership : ");
        add(type);
        type.setBounds(70, 66, 300, 30);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Membership....................................");
        add(jLabel2);
        jLabel2.setBounds(70, 10, 420, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/test.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        JPanel FinancialRecordPanel = new FinancialRecord(cusId);
        DataBase.changePanel(FinancialRecordPanel);
    } catch (SQLException ex) {
        Logger.getLogger(Membership1.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Membership1.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (User.mainUser.getIsEmp()==true)
        {JPanel MembershipPanel = new CustomerForRes(cusId);
         DataBase.changePanel(MembershipPanel);}
        else
        {
            JPanel MembershipPanel = new Customer();
            DataBase.changePanel(MembershipPanel);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DataBase.exitFrame();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cost;
    private javax.swing.JLabel end;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel start;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
