/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.DataBase;
import database.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class Program extends javax.swing.JPanel {

    /**
     * Creates new form Program
     */
    int cusId;
    public Program(int cusId) throws SQLException, ClassNotFoundException {
        initComponents();
        this.cusId=cusId;
        String sql1 = "select u.name from user as u , customers as c where u.userid =c.userId and  c.cusId  =  " + cusId;
        DatabaseAPI db = new DatabaseAPI();
        
        ResultSet set1 = db.read(sql1);
        while (set1.next()) {
            Name.setText("Program For " + set1.getString(1));
        }
        String sql=  " select * from programs  as p where p.programId  In (select c.programId  from customers as c where c.cusId=" + cusId+ ")";
     
        ResultSet set = db.read(sql);
        while (set.next())
        {
           
           breakfast.setText("Breakfast :" + set.getString(3));
           lunch.setText("Lunch :"+set.getString(4));
           Dinner.setText("Dinner :" + set.getString(5));
           notes.setText("Notes :"+set.getString(6));
        }
        if(!User.mainUser.getIsEmp())
        {
            jButton1.disable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        notes = new javax.swing.JLabel();
        Dinner = new javax.swing.JLabel();
        lunch = new javax.swing.JLabel();
        breakfast = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 550));
        setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("set new program");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(180, 340, 210, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(420, 420, 60, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(100, 420, 80, 40);

        notes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notes.setForeground(new java.awt.Color(0, 153, 153));
        notes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notes.setText("Notes :");
        notes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(notes);
        notes.setBounds(90, 210, 370, 110);

        Dinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dinner.setForeground(new java.awt.Color(0, 153, 153));
        Dinner.setText("Dinner :");
        add(Dinner);
        Dinner.setBounds(90, 180, 600, 17);

        lunch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lunch.setForeground(new java.awt.Color(0, 153, 153));
        lunch.setText("Lunch : ");
        add(lunch);
        lunch.setBounds(90, 140, 580, 17);

        breakfast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        breakfast.setForeground(new java.awt.Color(0, 153, 153));
        breakfast.setText("Breakfast : ");
        add(breakfast);
        breakfast.setBounds(90, 100, 610, 17);
        add(jLabel7);
        jLabel7.setBounds(110, 240, 270, 30);
        add(jLabel5);
        jLabel5.setBounds(100, 150, 230, 30);

        Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 102, 0));
        Name.setText("Program...............................................");
        add(Name);
        Name.setBounds(90, 20, 470, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/test.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 90, 648);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/big.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(450, 130, 330, 260);
    }// </editor-fold>//GEN-END:initComponents


    


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            // TODO add your handling code here:
            JPanel temp = new newProgram(cusId);
            DataBase.changePanel(temp);
        } catch (SQLException ex) {
            Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

                                      


                                          

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      if (User.mainUser.getIsEmp()==false)
        {JPanel CustomerPanel = new Customer();
        DataBase.changePanel(CustomerPanel);}
        else
        {
          try {
              JPanel CustomerPanel = new Reception();
              DataBase.changePanel(CustomerPanel);
          } catch (SQLException ex) {
              Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
    }                                        


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DataBase.exitFrame();
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dinner;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel breakfast;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lunch;
    private javax.swing.JLabel notes;
    // End of variables declaration//GEN-END:variables
}
