/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.Customers;
import database.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author dell
 */
public class Reception extends javax.swing.JPanel {

    /**
     * Creates new form Reception
     */
    public Reception() throws SQLException, ClassNotFoundException {
        initComponents();

        ResName.setText("Welcome " + User.mainUser.getName());
        String sql = "select * from user as u , customers as e where u.userId = e.userid; ";

        DatabaseAPI db = new DatabaseAPI();
        ResultSet set = db.read(sql);

        DefaultTableModel model = (DefaultTableModel) cus.getModel();
        while (set.next()) {
            int userId = set.getInt(1);
            String name = set.getString(2);
            String gender = "";
            if (set.getBoolean(4)) {
                gender = "Female";
            } else {
                gender = "Male";
            }

            String email = set.getString(5);

            String DOB = set.getString(6);
            String Hd = set.getString(8);
            int cusId = set.getInt(10);
            int age = LocalDateTime.now().getYear()-Integer.parseInt(DOB.substring(0, 4));
            String mem = "";
            if (Customers.getMemStates(cusId))
                mem = "Active";
            else
                mem = "Not Active";
            double blalance = Customers.getBalance(cusId);
            System.out.println(sql);
            model.addRow(new Object[]{userId,"cus"+cusId,name,mem,blalance, email,age,gender,DOB,Hd});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cus = new javax.swing.JTable();
        ResName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1040, 800));
        setRequestFocusEnabled(false);
        setLayout(null);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 870));
        jPanel1.setLayout(null);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 102, 0));
        jButton7.setText("Reports");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(310, 650, 180, 30);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(330, 240, 130, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Show Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 530, 180, 31);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 102, 0));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(268, 105, 198, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 110, 64, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 140, 103, 22);

        user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 51, 0));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(268, 136, 198, 28);

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 102, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(268, 167, 198, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 170, 64, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Age");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 200, 64, 22);

        cus.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cus.setForeground(new java.awt.Color(0, 153, 153));
        cus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "userId", "user name", "name", "Membership ", "Balance", "email", "age", "Gender", "dateOfBirth", "Join Date "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cus);
        if (cus.getColumnModel().getColumnCount() > 0) {
            cus.getColumnModel().getColumn(0).setMinWidth(0);
            cus.getColumnModel().getColumn(0).setPreferredWidth(0);
            cus.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 300, 830, 200);

        ResName.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ResName.setForeground(new java.awt.Color(255, 102, 0));
        ResName.setText("search for Customer .....");
        jPanel1.add(ResName);
        ResName.setBounds(160, 30, 363, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/Picture111.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(640, 30, 399, 240);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/ضضض.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 170, 970);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(120, 590, 100, 40);

        age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 102, 0));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age);
        age.setBounds(270, 200, 80, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Edit My Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(610, 560, 210, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("Change Password");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(610, 620, 210, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 102, 0));
        jButton6.setText("Add Customer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(310, 590, 180, 31);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 870);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            cus.setRowSorter(null);

        if (!name.getText().equals("")) {

            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) cus.getModel()));
            sorter.setRowFilter(RowFilter.regexFilter(name.getText(),2));
            cus.setRowSorter(sorter);

        }
        if (!email.getText().equals("")) {
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) cus.getModel()));
            sorter.setRowFilter(RowFilter.regexFilter(email.getText(),3));
            cus.setRowSorter(sorter);

        }
         if (!user.getText().equals("")) {

            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) cus.getModel()));
            sorter.setRowFilter(RowFilter.regexFilter(user.getText(),1));
            cus.setRowSorter(sorter);

        }
        if (!age.getText().equals("")) {
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) cus.getModel()));
            sorter.setRowFilter(RowFilter.regexFilter(age.toString(),3));
         
            cus.setRowSorter(sorter);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r  = cus.getSelectedRow();
        if (r!= -1 )
        {
             String empId =  (String) cus.getValueAt(r, 1);
        
            int id = id = Integer.parseInt( empId.substring(3));
            if (User.mainUser.getEmp().getRank()==1)
            {JPanel temp = new CustomerForRes(id);
            database.DataBase.changePanel(temp);}
            else
            {
                 try {
                     JPanel temp = new Program(id);
                     database.DataBase.changePanel(temp);
                 } catch (SQLException ex) {
                     Logger.getLogger(Reception.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(Reception.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
            JPanel  temp = new ChangePassword();
            database.DataBase.changePanel(temp);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         JPanel  temp = new NewCustomer();
            database.DataBase.changePanel(temp);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JPanel  temp = new Reports();
            database.DataBase.changePanel(temp);
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResName;
    private javax.swing.JTextField age;
    private javax.swing.JTable cus;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
