/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.Customers;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import static java.util.Calendar.MONTH;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class Reorts extends javax.swing.JPanel {

    /**
     * Creates new form Reorts
     */
    ArrayList <Integer> x=new ArrayList<Integer>();
    public Reorts() throws SQLException, ClassNotFoundException {
        initComponents();
        DatabaseAPI db = new DatabaseAPI();
           String sql=" select mem.memid ,mem.memname from membership as mem";
          ResultSet set = db.read(sql);
          while (set.next())
          {
              //System.out.println("ggh"+set.getString(2));
              mem.addItem(set.getString(2));
              x.add(set.getInt(1));
          }
      
          //long sum=0;
          
          
          
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mem = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        browse = new javax.swing.JTable();
        t = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(663, 648));
        setPreferredSize(new java.awt.Dimension(730, 670));
        setRequestFocusEnabled(false);
        setLayout(null);

        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(0, 153, 153));
        add(total);
        total.setBounds(80, 140, 60, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("get");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(340, 40, 60, 30);

        mem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mem.setForeground(new java.awt.Color(0, 153, 153));
        mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memActionPerformed(evt);
            }
        });
        add(mem);
        mem.setBounds(190, 40, 130, 30);

        browse.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        browse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        browse.setForeground(new java.awt.Color(0, 153, 153));
        browse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Customer Name", "Ended"
            }
        ));
        jScrollPane1.setViewportView(browse);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 200, 590, 330);

        t.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t.setForeground(new java.awt.Color(255, 102, 0));
        t.setText("Total Paid For It :");
        add(t);
        t.setBounds(60, 80, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Membership ");
        add(jLabel2);
        jLabel2.setBounds(70, 40, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/test.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -70, 70, 648);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/Picture111.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(390, 0, 399, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memActionPerformed
        // TODO add your handling code here:
        total.setText("");
        // browse.removeAll();

        
    }//GEN-LAST:event_memActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) browse.getModel();
        model.setRowCount(0);
        if(mem.getSelectedIndex() >= 0 )
        {
            try {
                int memId = x.get(mem.getSelectedIndex());
                String sql = "select cusId from memcus where memId = " +  memId;
                
                System.out.println("dddddddddddddddddd");
                DatabaseAPI db =new DatabaseAPI();
                ResultSet set = db.read(sql);
                while(set.next())
                {
                    System.out.println(">>>>>>>>>>>>>>>>" +set.getInt(1));
                 if(Customers.getMemStates(set.getInt(1), memId))   
                 {
                     
                     String name = "" ;
                     String sql2 = " select u.name from user as u ,customers as c where u.userid = c.userid and c.cusId = "+ set.getInt(1);
                     ResultSet set2 = db.read(sql2);
                     String ends = Customers.endDate(set.getInt(1));
                     while (set2.next())
                         name = set2.getString(1);
                         
                     model.addRow(new Object[]{
                         name , ends
                        
                    });
                 }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Reorts.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reorts.class.getName()).log(Level.SEVERE, null, ex);
            }

            
        }
               
      
               
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable browse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mem;
    private javax.swing.JLabel t;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
