/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import database.Customers;
import database.DataBase;
import database.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class SignUp extends javax.swing.JPanel {
     DefaultTableModel model ;
     
    /**
     * Creates new form SignUp
     */
    public SignUp() throws SQLException, ClassNotFoundException {
        
        initComponents();
         DatabaseAPI db = new DatabaseAPI();
        String sql = "SELECT  c.className,s.sectionId,s.numOfstudents,s.day,s.hour,s.age ,u.Name FROM sections  as s,classes as c,employee as e ,user as u where s.classId = c.classId and s.empid=e.empid and e.userid=u.userId";
        ResultSet set = db.read(sql);
       model=(DefaultTableModel) browse.getModel();
        while (set.next()) {
            String f=day(set.getInt(4));
            int k=LocalDateTime.now().getYear();
            
            if (LocalDateTime.now().getYear()-Integer.parseInt(((java.sql.Date)(User.mainUser.getDateOfBirth())).toString().substring(0, 4))>=set.getInt(6))
                //System.out.println(LocalDateTime.now().getYear()-Integer.parseInt(((java.sql.Date)(User.mainUser.getDateOfBirth())).toString().substring(0, 4)));
            model.addRow(new Object[]{set.getString(1), set.getString(2), set.getString(3), (f + " " + set.getString(5)), set.getString(7)});

        }
    }
    public String day(int i)
    {
        switch (i)
        {
            case 0: return "Saturday";
            case 1: return "Sunday";
            case 2: return "Monday";
            case 3: return "Tuesday";
            case 4: return "Wednesday";
            case 5 :return "Thursday";
            case 6: return "Friday";
            
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        success = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        browse = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(836, 649));
        setLayout(null);
        add(success);
        success.setBounds(180, 504, 230, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(450, 470, 90, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 153));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(80, 470, 80, 40);

        jButton2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(190, 400, 230, 40);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Cources Signing Up....................................................................................");
        add(jLabel3);
        jLabel3.setBounds(90, 60, 660, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/test.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 396, 648);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/big.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(490, 370, 346, 274);

        browse.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        browse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        browse.setForeground(new java.awt.Color(0, 153, 153));
        browse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Class Name", "Section Number", "Number Of Students", "ClassTime ", "Coach Name"
            }
        ));
        jScrollPane1.setViewportView(browse);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 150, 710, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             if (browse.getSelectedRow()!=-1)
             {
                 try {
                     String sec =  (String) browse.getValueAt(browse.getSelectedRow(), 1);
                     Customers.signForAClass(Integer.parseInt(sec),User.mainUser.getCus().getCusid());
                     success.setText("Successfully Signed Up!!!");
                 } catch (SQLException ex) {
                     success.setText("you can't sign for this class!!!");
                     //Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     success.setText("you can't sign for this class!!!");
                     //Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 

             }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       
         try {
             JPanel CustomerPanel = new Customer();
             DataBase.changePanel(CustomerPanel);
         } catch (SQLException ex) {
             Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DataBase.exitFrame();
    }//GEN-LAST:event_jButton4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable browse;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
